### ISSUE TITLE
Long Term React Homework Exercise

### ISSUE THREAD

**Issue by st-quando** [ST-React-Learning/final-project-docs#2]
# Basic Information:
We will make the Ecolife web application similar with the below link.
http://demo.posthemes.com/pos_ecolife/layout2/en/

## API:
domain: https://604b401bee7cb900176a1a9e.mockapi.io/api/v1/
get Cagetories: GET /cagetories
get Products: GET /products

## Prerequisites
- Typescript
- Scss
- React Functional Component
- `react-scripts`  (npx)

**Comment by st-quando** [comment]
## Phase 1:

**Comment by st-quando** [comment]
## Phase 2:
### Deadline
3 days
### Content
Making UI with introduction section for **PC**
Checklist:
- [ ] Build react base code `ts`, `scss` with `react-scripts`
- [ ] Header
- [ ] Banner
- [ ] Sub menu when hover `Fresh Vegetables`
- [ ] No need carousel, only put 1 image for banner


![Screen Shot 2021-03-09 at 2 05 52 PM](https://user-images.githubusercontent.com/62696504/110431647-a5f10d80-80e0-11eb-98f0-6c0a8894e004.png)

**Comment by quan-tranlinh** [comment]
URL of Categories not correct. (Typo).
Correct URL : 

- https://604b401bee7cb900176a1a9e.mockapi.io/api/v1/categories

**Comment by st-quando** [comment]
## Phase 3:
### Deadline
3 days
### Content
- Only call `getCategories` 1 time when open app and save result into redux for reusing.
Each product have `type` field with 1,2,3,4. Based on the result of categories, bind the name of category into each product.
- Write a HOC to handle the loading data of products:
 calling api => show loading
 called api & empty list => show "there is no data"
 called api & array list => show products UI.
NOTES: prevent the case calling api but show  "There is no data"
